name: Cypress
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build-and-run-tests:
    runs-on: ubuntu-16.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: forge
          MYSQL_DATABASE: forge
          DB_HOST: 127.0.0.1
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Copy ENV Laravel Configuration for CI
        env:
          MYSQL_DATABASE: forge
          DB_CONNECTION: mysql
          DB_DATABASE: forge
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: forge
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_KEY: ${{ secrets.PLAID_KEY }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
        run: |
          php -r "file_exists('.env') || copy('.env.ci', '.env');"
          echo 'STRIPE_KEY=${STRIPE_KEY}' >> .env
          echo 'STRIPE_SECRET=${STRIPE_SECRET}' >> .env
          echo 'PLAID_CLIENT_ID=${PLAID_CLIENT_ID}' >> .env
          echo 'PLAID_KEY=${PLAID_KEY}' >> .env
          echo 'PLAID_SECRET=${PLAID_SECRET}' >> .env

      - name: Login to Laravel Nova
        run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
        env:
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist && npm ci

      - name: Generate key
        run: php artisan key:generate

      - name: Migrate MySQL DB
        env:
          MYSQL_DATABASE: forge
          DB_CONNECTION: mysql
          DB_DATABASE: forge
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: forge
        run: |
        php artisan migrate:fresh
        php artisan db:seed --class=CypressSeeder

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: false
          start: php artisan serve
          wait-on: http://localhost:8000
          config-file: cypress.json

      - uses: actions/upload-artifact@master
        # there might be no screenshots created when:
        # - there are no test failures
        # so only upload screenshots if previous step has failed
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
      # video should always be generated
      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
