name: Production CI

on:
  push:
    branches: [ 'main' ]

jobs:

  laravel-tests:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 20
          continue-after-seconds: 240
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Login to Laravel Nova
        run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
        env:
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_KEY: ${{ secrets.PLAID_KEY }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
        run: php artisan test --parallel

  deploy-production:

    runs-on: ubuntu-latest

    needs: laravel-tests

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME_PRODUCTION }}
          script: |
            cd /home/bitnami/htdocs/CreatorCore
            php artisan down
            git checkout -f
            git pull
            composer install --no-dev
            php artisan migrate --force
            php artisan optimize:clear
            rm -rf public/storage
            php artisan storage:link
            php artisan optimize
            php artisan up
